//USER ACTIONS
export const SET_USERDATA = "SET_USERDATA";
export const SET_ERROR_MESSAGE = "SET_ERROR_MESSAGE";
export const ATTEMPT_LOGIN = "ATTEMPT_LOGIN";
export const LOGIN = "LOGIN";
export const SET_PAGE = "SET_PAGE";

//POLL ACTIONS
export const SET_QUESTION = "SET_QUESTION";
export const SET_POLL_INPUT = "SET_POLL_INPUT";
export const CREATE_NEW_QUESTION = "CREATE_NEW_QUESTION";
export const CREATE_EMPTY_QUESTION = "CREATE_EMPTY_QUESTION";
export const SET_CHECK_BOX = "SET_CHECK_BOX";
export const SET_MULTIPLE_CHOICE = "SET_MULTIPLE_CHOICE";
export const ADD_MULTIPLE_CHOICE_INPUT = "ADD_MULTIPLE_CHOICE_INPUT";
export const SET_SNACKBAR_MESSAGE = "SET_SNACKBAR_MESSAGE";
export const SAVE_POLL = "SAVE_POLL";
export const SET_LOADING = "SET_LOADING";
export const CLEAR_POLL = "CLEAR_POLL";
export const SET_POLLS = "SET_POLLS";
export const SET_RESULTS = "SET_RESULTS";
export const EDIT_POLL = "EDIT_POLL";

//USER ACTIONS
export const SET_NAME = "SET_NAME";
export const SET_POLLS_USER = "SET_POLLS_USER";
export const SET_LOADING_USER = "SET_LOADING_USER";
export const SET_PAGE_USER = "SET_PAGE_USER";
export const SET_CURRENT_POLL = "SET_CURRENT_POLL";
export const SET_CURRENT_QUESTION = "SET_CURRENT_QUESTION";
export const SET_USER_ANSWER = "SET_USER_ANSWER";
export const SAVE_USER_POLL = "SAVE_USER_POLL";
export const CLEAR_STATE = "CLEAR_STATE";
